/* Gobals  */
var gMenuItem;          // Maintain menu's data
var menuFirst = true;     // switch 'active' class on first menu item

/**
 * onReady
 * 
 * When website loads, you get an empty page, this function loads 
 * the menu (based on json), main page and footer.
 * All those pages are generated by the backend
 */
$(function () {
  // Load menu from json file
  $.get("json/menu.json", function (datas, status) {
    gMenuItem = datas.menuItems; // Store menu for future use
    //$(menu).append("<div id='navbarContent' class='collapse navbar-collapse'></div>");
    datas.menuItems.forEach(function (menuItem) {
      // Add first levels menuitems
      setItem("#menu", menuItem);
    }); // foreach
  });
  // Load main page  
  $("#content").load("content/main.html");
  // Load footer
  $("#footer").load("content/footer.html");

  // Allow multi-level menu 
  // TODO see a much proper way than timeOut
  setTimeout(function(){
    // Multi Level dropdowns - add from Bootstrap 4 default
    // This must be launch after DOM is ready (wait 250ms)
    $("ul.dropdown-menu [data-toggle='dropdown']").on("click", function (event) {
      event.preventDefault();
      event.stopPropagation();

      $(this).siblings().toggleClass("show");

      if (!$(this).next().hasClass('show')) {
        $(this).parents('.dropdown-menu').first().find('.show').removeClass("show");
      }
      $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function (e) {
        $('.dropdown-submenu .show').removeClass("show");
      });

    });
  },250);
  
});

/****************
* menu creation *
*****************/
/**
 *  setItem(menu, item)
 * 
 * fill menu <nav> with firstlevel items
 *
 * @param  {string}  menu       class of current menu
 * @param  {object}  item       item to add on menu
 * @return {void}
 */
function setItem(menu, item) {

  if (item.type != "menu") {
    // simple <li> line
    // <li class="nav-item"><a href="#" class="nav-link" onclick="loadContent();return false;">About</a></li>
    li = "<li class='nav-item'><a href='#' class='nav-link' ";
    li += "onclick='loadContent(\"" + item.name + "\");return false;'>" + item.label + "</a></li>";
    $(menu).append(li);
  }
  else {
    // <li> line plus <ul> sub-menu
    li = "<li class='nav-item dropdown'>";
    li += "<a id='menu-" + item.name + "' href='#' data-toggle='dropdown'";
    li += " aria-haspopup='true' aria-expanded='false' class='nav-link ";
    li += "dropdown-toggle'>" + item.label + "</a>";
    li += "<ul aria-labelledby='menu-" + item.name + "' id='m-" + item.name + "' ";
    li += "class='dropdown-menu border-0 shadow'></ul></li>";
    $(menu).append(li);
    // Time to call sub-menu items 
    item.menuItems.forEach(function (menuItem) {
      setSubMenuItems("#m-" + item.name, menuItem);
    });   
  }
}

/*
* setSubMenuItems(menu,item)
*
* re-entrant function, allows to fill sub-menus
*
* @param  {string}   menu     menu id name
* @param  {object}   item     menuItem object
* @return {void}
*/
function setSubMenuItems(menu, item) {
  if (item.type != "menu") {
    // simple <li> line
    // <li> <a class="dropdown-item" href="#" onclick="loadContent();return false;">About</a></li>
    li =  "<li><a class='dropdown-item' href='#' ";
    li += "onclick='loadContent(\"" + item.name + "\");return false;'>" + item.label + "</a></li>";
    $(menu).append(li);
  }
  else {
    li =  "<li class='dropdown-submenu'>";
    li += "<a id='menu-"+item.name+"' href='#' role='button' ";
    li += "data-toggle='dropdown' aria-haspopup='true' ";
    li += "aria-expanded='false' class='dropdown-item dropdown-toggle'>";
    li += item.label+"</a><ul aria-labelledby='menu-"+item.name+"' ";
    li += "class='dropdown-menu border-0 shadow' id='m-"+item.name+"'></ul>";
    $(menu).append(li);
    // Time to call sub-menu items 
    item.menuItems.forEach(function (menuItem) {
      setSubMenuItems("#m-" + item.name, menuItem);
    });   
  }
}

/**
 * loadContent
 * 
 * this function loads content in content folder in the <div> identified by
 * contend id
 *  
 * @param {text} id   name of file to be loaded
 * @return void
 */
function loadContent(id) {
  $("#content").text("Chargement : " + id);
  $("#content").load("content/" + id + ".html");
}